var colors = require('colors');

module.exports = [
	'                                        '.cyan,
	'                             IIII       '.cyan,
	'                  ZZ~      ?IIIIII?     '.cyan,
	'            : I7=?+Z$$$7ZI7IIIII  ,I:   '.cyan,
	'            ,7+?IIII$$$$IIIIIIII, III7, '.cyan,
	'               +?IIIIIIIIIIIIIIIIIII,   '.cyan,
	'                 I7IIIIIIIIIIIIIIII     '.cyan,
	'                  IIIIIIIIIII?+:,=I     '.cyan,
	'               =?IIIIIIIIIII:::::::     '.cyan,
	'  ,=       ,=IIIIIIIIIIIII:::::,:,      '.cyan,
	'    ~?I??IIIIIIIIIIIIIIII:::,:::        '.cyan,
	'       +?IIIIIIIIIIIIIII:::::::         '.cyan,
	'          ~IIIIIIIIIIIII:::::           '.cyan,
	'                ~?IIIIII=               '.cyan,
	'                                        '.cyan,
	'Simple tool for making tweets from the shell',
	'https://github com/voronianski/node-tweet-cli',
	'author: <dmitri.voronianski@gmail.com>',
	'',
	'Usage:'.cyan.bold.underline,
	'',
	'To log into your twitter account'.cyan,
	' tweet login',
	'',
	'To log out from your twitter account'.cyan,
	' tweet logout',
	'',
	'To start tweeting'.cyan,
	' tweet create'
];
